arrowParens: 'always'
bracketSpacing: true
htmlWhitespaceSensitivity: 'css'
jsxBracketSameLine: true
jsxSingleQuote: false
parser: 'typescript'
printWidth: 80
proseWrap: 'preserve'
semi: true
singleQuote: true
tabWidth: 4
trailingComma: 'all'
